formatter_currency <- c("loyer_annuel", "charges_annuelles", "taxes_foncieres", "charges_courrantes",
                        "remboursement_pret", "CI", "tresorie", "pret_restant", "rembourse")

lisezmoi <- rbind.data.frame(
  c("loyer_annuel", "Loyer annuel initial, augmenté du taux d'inflation chaque année"),
  c("charges_annuelles", "Charges annuelles fixes, augmenté du taux d'inflation chaque année"),
  c("taxes_foncieres", "loyer_annuel * taux_taxes_foncieres / 12"),
  c("charges_courrantes", "loyer_annuel * charges_courrantes_percentage"),
  c("remboursement_pret", "mensualite * 12"),
  c("CI", "Credit d'impôts: (cout_construction + cout_non_construction_inclut_CI) * taux_credit_impot"),
  c("tresorie", "Trésorie disponnible: loyer_annuel - charges_annuelles - taxes_foncieres - charges_courrantes - remboursement_pret + CI"),
  c("pret_restant", "Montant du crédit à restant (cout_total_credit - remboursement du prêt)"),
  c("rembourse", "Montant du prêt remboursé"),
  c("Coût de construction", "Coût de construction"),
  c("Coût non construction, inclût crédit d'impôts", "Terrain, frais architecte, etc."),
  c("Coût non construction, hors crédit d'impôts", "Conseils, etc."),
  c("Imprévu (% coût de construction)", "Imprévu"),
  c("Coût total construction", "Coût de construction + Coût non construction, inclût crédit d'impôts + Coût non construction, hors crédit d'impôts + Imprévu*Coût de construction" ),
  c("Apport personnel", "Montant de l'apport personnel"),
  c("Montant de la demande de prêt", "Coût total construction - Apport personnel"),
  c("Nombre d'années prêt", ""),
  c("Nombre de mensualités", "Nombre d'années * 12"),
  c("Taux d'interet", ""),
  c("Mensualité des remboursements", "  (capital * taux / 12) / (1 - (((1 + (taux / 12)))^(-nbr_mensualite)))"),
  c("Coût total prêt", "Mensualité des remboursements * Nombre de mensualités"),
  c("Taux crédit d'impôts", ""),
  c("Montant crédit d'impôts", "(Coût de construction + Coût non construction, inclût crédit d'impôts) * Taux crédit d'impôts"),
  c("Revenu annuel", "Loyer annuel initial"),
  c("Pourcentage d'augmentation loyer annuel", "Inflation estimée"),
  c("Charge courrantes (en % du loyer)", "Assurances, entretiens, agence, etc."),
  c("Taxes foncières (en nombre de loyer mensuel)", "Estimation du prix de la taxe foncière en loyer"),
  c("Charge annuelle initiale", "Charge fixe annuelle, comptable, etc."),
  make.row.names = F) |>
  `names<-`(c("Item", "Définition"))
